apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://8dec3ae13ff4e8d6d94638c20ffff12b-3000.maxwell.assessments.scaler.com/john_doe/apps-of-apps.git  # Replace with your GitHub account if needed
    path: backend                                 # Path within the repository
    targetRevision: main                                     # Replace "main" with the appropriate branch or tag
  destination:
    server: https://kubernetes.default.svc                     # In-cluster Kubernetes API server
    namespace: default                          # Target namespace
  syncPolicy:
    automated:
      prune: true                                              # Prune resources not in the source
      selfHeal: true                                           # Automatically fix drift
    syncOptions:
      - CreateNamespace=true 
